### ISSUE TITLE
Edición Estudios Teologicos Previos

### ISSUE THREAD

**Issue by JonyMedina** [JonyMedina/ISUM#1]
Estudios Teologicos Previos-- > tiene que tener edición, puede ser mas de uno por alumno

**Comment by JonyMedina** [comment]
1)
--> crear action get AdministrarEstudios()
--> crear viewModel si no existe y pre-cargarlo para mostrar
--> Crear view

**Comment by JonyMedina** [comment]
Terminado el "Grueso" de la funcionalidad.
Falta detalles de UI y Testing

**Comment by lpietrella** [comment]
Yo me ocupo de la UI

**Comment by lpietrella** [comment]
LA UI esta terminada.
Cerramos el issue
