### ISSUE TITLE
B.2 - Nueva Inscripcion y Confirmar Inscripcion

### ISSUE THREAD

**Issue by lpietrella** [JonyMedina/ISUM#17]
Pantallas B.2 y B.2.1 del adjunto
[Etapa B.pdf](https://github.com/JonyMedina/ISUM/files/2466006/Etapa.B.pdf)

Datos a considerar que se necesitan pasar al metodo para el envio del mail:
Nombre_RepresentantePais
Seminario_Nombre
Seminario_FechaInicio
Seminario_Sede
Inscripto_NombreCompleto
Inscripto_FechaNacimiento

**Comment by lpietrella** [comment]
Falta generar metodo donde se va a enviar el email al representante de pais.

**Comment by JonyMedina** [comment]
cree este metodo en la clase CommonHelper EnviarMailInscripcion(InscripcionViewModel datosInscripcion)
que recibe el objeto ya todo cargado. Avisame cualquier cosa para implementar el envio de mail.

**Comment by lpietrella** [comment]
Lista esta funcionalidad
