### ISSUE TITLE
Corregir Relacion Inscripciones-Documentos

### ISSUE THREAD

**Issue by lpietrella** [JonyMedina/ISUM#29]
- Sacar el FK de Docs
- Adicionar FK en Inscripciones pra que cada inscripcion tenga un IdDoc asociado
- Al grabar una inscripcion agregar a los docs del usuario uno de Tipo Doc id = 4 y con el nombre: "Inscripcion [ID] Seminario X"

**Comment by JonyMedina** [comment]
@lpietrella para charlar despues.. al momento de guardar no tengo el "Inscripcion ID" hasta despues de impactar en la DB. Vale la pena hacer alguna manganeta para poner ese id? o le ponemos otra cosa...

**Comment by lpietrella** [comment]
Listo
