### ISSUE TITLE
C. Crear Nuevos Seminarios y Aceptar/Rechazar Alumnos

### ISSUE THREAD

**Issue by lpietrella** [JonyMedina/ISUM#34]
[Etapa C.pdf](https://github.com/JonyMedina/ISUM/files/2605854/Etapa.C.pdf)

**Comment by JonyMedina** [comment]
Se subieron fixes en la pantalla de nuevo Seminario:

- Nuevo Seminario
- Agregar Director (done)
- Validar que este mostrando solo los profesores Y directores (tienene el rol)
- Cuando cargo pantalla no esta filtrando las materias por seminario.
- Le tiro guardar sin elegir profesores y no creo registros en CursadaMateria. Cambiar el foreach - Tiene que crear con Profesor = Null

**Comment by lpietrella** [comment]
Cerrado
