### ISSUE TITLE
Issue con Fecha de Nacimiento

### ISSUE THREAD

**Issue by lpietrella** [JonyMedina/ISUM#4]
Cambio la fecha a algo como 1976 y la guardo y muestra "01-01-0001"
Si salgo y vuelvo a enrar sigue mostrando la fecha antigua sin grabar

**Comment by lpietrella** [comment]
sigue jodiendo la fecha... 
Lo corri localmente tengo el SO en ingles
<img width="452" alt="issue fecha" src="https://user-images.githubusercontent.com/13419474/46576627-ec3c6280-c9a4-11e8-92cf-5e6f2a6b585d.png">

**Comment by JonyMedina** [comment]
Hice una pruebita muy rapida... mañana lo probamos bien a ver que onda

**Comment by lpietrella** [comment]
Funciona
