### ISSUE TITLE
Pantalla de listado de usuarios/alumnos

### ISSUE THREAD

**Issue by lpietrella** [JonyMedina/ISUM#7]
Pantalla de listado de usuarios/alumnos para poder editar cuentas de alumnos por un administrador

**Comment by JonyMedina** [comment]
) armar get obtener listado de usuarios
) armar view mostrar grilla usuarios (con boton "ver detalles" por linea)
) en el get de Legajo en el account controller que reciba por ID de usuario......

**Comment by JonyMedina** [comment]
@lpietrella terminada la funcionalidad de end-to-end... Quedaria mejorar la "UX" y hacer un buen testing. Me parece que conviene crear dos issues separados para trackear eso.
